# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
